appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.8.0
appReplicas: 2
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"
probePeriodSeconds: 5
resourceRequestsCpu:  50m
resourceRequestsMemory: 64Mi
resourceLimitsCpu: 140m
resourceLimitsMemory: 128Mi

servicePort: 50051